import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';
import { SessionProvider } from 'next-auth/react';
import Header from '@/app/(layout)/_components/Header';
import { auth } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <head>
        <title>Garden Buddy</title>
        <link rel="icon" href="/app/icon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Header />
          <main className={styles.main}>{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
